sudo: required

services:
  - docker

before_install: 
  - docker build -t chriscastle8/docker_react -f Dockerfile.dev .

script: 
  - docker run -e CI=TRUE chriscastle8/docker_react  npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-554682831316"
  bucket_path: "Docker-react"
  on: 
    branch: master
  access_key_id: $$AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"